### ISSUE TITLE
V1.7.0 review

### ISSUE THREAD

**Issue by clangenb** [ajuna-network/ajuna-runtimes-bajun#1]
## Runtime
* I guess milliseconds per block should stay 12 seconds: https://github.com/ajuna-network/ajuna-runtimes-bajun/blob/0890b099b31a4f003f038be5d99d961e06603ab2/runtime/bajun/src/lib.rs#L225
* As long as async backing isn't enabled we have to stay at 500ms total weight time: https://github.com/ajuna-network/ajuna-runtimes-bajun/blob/0890b099b31a4f003f038be5d99d961e06603ab2/runtime/bajun/src/lib.rs#L254
* Why did the basecall filter implementation change? https://github.com/ajuna-network/ajuna-runtimes-bajun/blob/0890b099b31a4f003f038be5d99d961e06603ab2/runtime/bajun/src/lib.rs#L308
* Allow multiple slots per slot has to be false: https://github.com/ajuna-network/ajuna-runtimes-bajun/blob/0890b099b31a4f003f038be5d99d961e06603ab2/runtime/bajun/src/lib.rs#L622
* Just in case: message queue should not have the same index as its predecessor the dmp-queue: https://github.com/ajuna-network/ajuna-runtimes-bajun/blob/0890b099b31a4f003f038be5d99d961e06603ab2/runtime/bajun/src/lib.rs#L898C1-L899C43

## ProxyType
* Why is orml commented out now? https://github.com/ajuna-network/ajuna-runtimes-bajun/blob/0890b099b31a4f003f038be5d99d961e06603ab2/runtime/bajun/src/proxy_type.rs#L66

**Comment by DidacSF** [comment]
The issue related to BaseCall filter implementation is because we had this filter added in a more recent version and I though it would be nice to already have it in place

**Comment by clangenb** [comment]
Ok, fine with me, still I prefer independent PRs for changes like that. ;)
